In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
houses = pd.read_csv('trains.csv')
holdout_set = pd.read_csv('test.csv')

In [3]:
holdout_set.corr()

Id       PID  MS SubClass  Lot Frontage  Lot Area  \
Id               1.000000  0.168951    -0.022145      0.035015  0.031120   
PID              0.168951  1.000000     0.003957     -0.110600  0.053072   
MS SubClass     -0.022145  0.003957     1.000000     -0.492924 -0.151110   
Lot Frontage     0.035015 -0.110600    -0.492924      1.000000  0.427936   
Lot Area         0.031120  0.053072    -0.151110      0.427936  1.000000   
Overall Qual    -0.018365 -0.256437     0.049322      0.254179  0.089771   
Overall Cond     0.023110  0.098941    -0.060988     -0.121919 -0.060215   
Year Built      -0.025396 -0.334734     0.038828      0.150638  0.005288   
Year Remod/Add  -0.040864 -0.110412     0.039648      0.107458 -0.024199   
Mas Vnr Area    -0.020339 -0.189961     0.016792      0.231048  0.068696   
BsmtFin SF 1     0.000417 -0.127274    -0.058239      0.218800  0.164158   
BsmtFin SF 2    -0.009488  0.024334    -0.077752      0.067070  0.145071   
Bsmt Unf SF     -0.002469 -0.029784    -0.105865      0.091441 -0.002267   
Total Bsmt SF   -0.006109 -0.154230    -0.202164      0.348470  0.232725   
1st Flr SF       0.008535 -0.132011    -0.251201      0.442173  0.272773   
2nd Flr SF       0.018769  0.001472     0.300158      0.063386  0.039080   
Low Qual Fin SF  0.019537  0.006495     0.009771      0.025983  0.001541   
Gr Liv Area      0.023279 -0.095568     0.067745      0.383553  0.233791   
Bsmt Full Bath  -0.062903 -0.054606    -0.013277      0.102279  0.146275   
Bsmt Half Bath   0.051201  0.020757     0.033467     -0.006501  0.024475   
Full Bath       -0.014577 -0.152897     0.118968      0.258680  0.137184   
Half Bath       -0.033212 -0.173586     0.166728      0.055099  0.013613   
Bedroom AbvGr    0.027565 -0.000566    -0.057143      0.287008  0.138467   
Kitchen AbvGr   -0.050388  0.093963     0.270326     -0.017877 -0.031414   
TotRms AbvGrd    0.029347 -0.032810     0.025645      0.331082  0.191723   
Fireplaces       0.022463 -0.080508    -0.039277      0.265237  0.217405   
Garage Yr Blt   -0.053298 -0.269587     0.099690      0.097784 -0.029365   
Garage Cars     -0.007822 -0.258832    -0.037145      0.336713  0.133590   
Garage Area     -0.012850 -0.233453    -0.091022      0.358552  0.144158   
Wood Deck SF    -0.016888 -0.075710    -0.064854      0.133622  0.170299   
Open Porch SF    0.049787 -0.049251    -0.002328      0.114151  0.051866   
Enclosed Porch   0.017678  0.188008     0.009224      0.043091  0.031631   
3Ssn Porch      -0.030103 -0.025407    -0.056818      0.020755  0.011843   
Screen Porch    -0.010104  0.015697    -0.080313      0.081616  0.038185   
Pool Area        0.043990 -0.028268     0.000309      0.221348  0.064540   
Misc Val         0.009717 -0.038563    -0.033523      0.021664  0.033099   
Mo Sold          0.146970 -0.093329    -0.030719      0.080486  0.005257   
Yr Sold         -0.976545  0.011728     0.016337     -0.046803 -0.015004   

                 Overall Qual  Overall Cond  Year Built  Year Remod/Add  \
Id                  -0.018365      0.023110   -0.025396       -0.040864   
PID                 -0.256437      0.098941   -0.334734       -0.110412   
MS SubClass          0.049322     -0.060988    0.038828        0.039648   
Lot Frontage         0.254179     -0.121919    0.150638        0.107458   
Lot Area             0.089771     -0.060215    0.005288       -0.024199   
Overall Qual         1.000000     -0.123447    0.582711        0.532887   
Overall Cond        -0.123447      1.000000   -0.363888        0.059605   
Year Built           0.582711     -0.363888    1.000000        0.572496   
Year Remod/Add       0.532887      0.059605    0.572496        1.000000   
Mas Vnr Area         0.411854     -0.134353    0.279747        0.165114   
BsmtFin SF 1         0.297939     -0.063312    0.291024        0.114552   
BsmtFin SF 2        -0.069813      0.027022   -0.040255       -0.073678   
Bsmt Unf SF          0.254227     -0.152081    0.109026        0.177491   
Total Bs

In [4]:
features = ['Overall Qual', 'Year Built']
x= houses [features]
y = houses ['SalePrice']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(x,y)

In [6]:
from sklearn.model_selection import cross_val_score

In [7]:
x.isnull().sum()

Overall Qual    0
Year Built      0
dtype: int64

In [8]:
houses['Street'].value_counts()

Pave    2044
Grvl       7
Name: Street, dtype: int64

In [9]:
from sklearn.linear_model import Lasso

In [10]:
lasso=Lasso()

In [12]:
scores = cross_val_score(lasso, X_train, y_train)
print(scores)
print(scores.mean())

[0.64206476 0.64130568 0.65583392]
0.6464014525354219


In [14]:
lasso.fit(x,y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [15]:
lasso.coef_

array([39764.35984929,   368.71449919])

In [16]:
holdout_set.head()

Id        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0  2658  902301120          190        RM          69.0      9142   Pave   
1  2718  905108090           90        RL           NaN      9662   Pave   
2  2414  528218130           60        RL          58.0     17104   Pave   
3  1989  902207150           30        RM          60.0      8520   Pave   
4   625  535105100           20        RL           NaN      9500   Pave   

  Alley Lot Shape Land Contour    ...     3Ssn Porch Screen Porch Pool Area  \
0  Grvl       Reg          Lvl    ...              0            0         0   
1   NaN       IR1          Lvl    ...              0            0         0   
2   NaN       IR1          Lvl    ...              0            0         0   
3   NaN       Reg          Lvl    ...              0            0         0   
4   NaN       IR1          Lvl    ...              0          185         0   

  Pool QC Fence Misc Feature Misc Val Mo Sold  Yr Sold  Sale Type  
0     NaN   NaN          NaN        0       4     2006        WD   
1     NaN   NaN          NaN        0       8     2006        WD   
2     NaN   NaN          NaN        0       9     2006        New  
3     NaN   NaN          NaN        0       7     2007        WD   
4     NaN   NaN          NaN        0       7     2009        WD   

[5 rows x 80 columns]

In [17]:
X_pred = pd.DataFrame(holdout_set[features])

In [25]:
y_preds =lasso.predict(X_pred)

y_preds

array([154257.53517511, 139197.04677183, 229418.48694704, 119286.46381535,
       173799.4036324 ,  97589.11442657,  92427.11143785, 139197.04677183,
       228681.05794865, 178961.40662112, 184123.40960984, 159788.25266303,
       170480.97313966, 227206.19995188, 159419.53816383, 131822.75678795,
       165318.97015094, 131454.04228875, 173061.97463401, 223462.24889626,
       135878.61627908, 133297.61478472, 184860.83860823, 176011.69062757,
       229787.20144623, 137353.47427586,  78415.96046848, 103431.74035   ,
       173799.4036324 ,  47869.46309904,  97220.39992738,  80259.53296445,
       182960.46004858, 137722.18877505, 227574.91445107, 229418.48694704,
        78415.96046848,  87633.82294833, 130347.89879117, 226837.48545268,
       190760.27059533, 226468.77095349, 132560.18578634, 129610.46979278,
       222412.91146235,  96851.68542818, 227574.91445107, 134772.4727815 ,
       131454.04228875, 134035.04378311, 121867.46530971, 226411.96488981,
       269551.56129552, 1

In [26]:
pd.read_csv('sample_sub_reg.csv', index_col='Id')

SalePrice
Id               
2     181479.1217
4     181479.1217
6     181479.1217
7     181479.1217
17    181479.1217
18    181479.1217
22    181479.1217
27    181479.1217
31    181479.1217
36    181479.1217
39    181479.1217
40    181479.1217
42    181479.1217
46    181479.1217
53    181479.1217
58    181479.1217
61    181479.1217
72    181479.1217
79    181479.1217
80    181479.1217
82    181479.1217
83    181479.1217
85    181479.1217
88    181479.1217
92    181479.1217
93    181479.1217
95    181479.1217
102   181479.1217
103   181479.1217
106   181479.1217
...           ...
2825  181479.1217
2828  181479.1217
2831  181479.1217
2843  181479.1217
2845  181479.1217
2847  181479.1217
2855  181479.1217
2856  181479.1217
2859  181479.1217
2865  181479.1217
2867  181479.1217
2869  181479.1217
2870  181479.1217
2874  181479.1217
2876  181479.1217
2889  181479.1217
2892  181479.1217
2895  181479.1217
2898  181479.1217
2901  181479.1217
2902  181479.1217
2908  181479.1217
2909  181479.1217
2916  181479.1217
2917  181479.1217
2919  181479.1217
2921  181479.1217
2922  181479.1217
2925  181479.1217
2928  181479.1217

[879 rows x 1 columns]

In [27]:
df= pd.DataFrame()

In [28]:
myids= holdout_set['Id']

In [29]:
df['Id']=myids

In [30]:
df.head()

Id
0  2658
1  2718
2  2414
3  1989
4   625

In [31]:
df['SalePrice']=y_preds

In [32]:
df

Id      SalePrice
0    2658  154257.535175
1    2718  139197.046772
2    2414  229418.486947
3    1989  119286.463815
4     625  173799.403632
5     333   97589.114427
6    1327   92427.111438
7     858  139197.046772
8      95  228681.057949
9    1568  178961.406621
10   2482  184123.409610
11   1364  159788.252663
12   2584  170480.973140
13    818  227206.199952
14   2673  159419.538164
15   2089  131822.756788
16   1297  165318.970151
17    790  131454.042289
18   2616  173061.974634
19    720  223462.248896
20    222  135878.616279
21    557  133297.614785
22   1148  184860.838608
23   2766  176011.690628
24    534  229787.201446
25   1452  137353.474276
26    630   78415.960468
27   2648  103431.740350
28    125  173799.403632
29   1904   47869.463099
..    ...            ...
849   933  180067.550119
850  2784  179330.121120
851   972  186704.411104
852   599  175274.261629
853  2614  172324.545636
854  2582  139934.475770
855  1409  157207.251169
856   175   36808.028123
857   352  266233.130803
858   976   96851.685428
859  2134  228312.343449
860   984  142146.762765
861  2396  307841.063148
862  1673  226468.770953
863   404  136616.045277
864   607  133297.614785
865   814  139934.475770
866   868  227943.628950
867  2271  185966.982106
868  1633  221306.767965
869   337  142146.762765
870  2765  134403.758282
871  1746  228681.057949
872   368  269920.275795
873  2806  228312.343449
874  1662  177855.263124
875  1234  174905.547130
876  1373  135878.616279
877  1672   97220.399927
878  1939  131085.327790

[879 rows x 2 columns]

In [33]:
df.set_index('Id', inplace= True)

In [34]:
df.to_csv('./my_preds5.csv')