In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
houses = pd.read_csv('trains.csv')
holdout_set = pd.read_csv('test.csv')

In [5]:
houses.head()

Id        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley  \
0  109  533352170           60        RL           NaN     13517   Pave   NaN   
1  544  531379050           60        RL          43.0     11492   Pave   NaN   
2  153  535304180           20        RL          68.0      7922   Pave   NaN   
3  318  916386060           60        RL          73.0      9802   Pave   NaN   
4  255  906425045           50        RL          82.0     14235   Pave   NaN   

  Lot Shape Land Contour    ...     Screen Porch Pool Area Pool QC Fence  \
0       IR1          Lvl    ...                0         0     NaN   NaN   
1       IR1          Lvl    ...                0         0     NaN   NaN   
2       Reg          Lvl    ...                0         0     NaN   NaN   
3       Reg          Lvl    ...                0         0     NaN   NaN   
4       IR1          Lvl    ...                0         0     NaN   NaN   

  Misc Feature Misc Val Mo Sold Yr Sold  Sale Type  SalePrice  
0          NaN        0       3    2010        WD      130500  
1          NaN        0       4    2009        WD      220000  
2          NaN        0       1    2010        WD      109000  
3          NaN        0       4    2010        WD      174000  
4          NaN        0       3    2010        WD      138500  

[5 rows x 81 columns]

In [38]:
features = ['Overall Qual',]
x= houses [features]
y = houses ['SalePrice']

In [37]:
houses['Overall Qual'].value_counts()

5     563
6     506
7     431
8     250
4     159
9      77
3      29
10     23
2       9
1       4
Name: Overall Qual, dtype: int64

In [10]:
X_train, X_test, y_train, y_test = train_test_split(x,y)

In [11]:
from sklearn.model_selection import cross_val_score

In [12]:
x.isnull().sum()

Overall Qual    0
dtype: int64

In [13]:
houses['Street'].value_counts()

Pave    2044
Grvl       7
Name: Street, dtype: int64

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
linereg = LinearRegression()

In [16]:
scores = cross_val_score(linereg, X_train, y_train)
print(scores)
print(scores.mean())

[0.63969493 0.65870216 0.62595989]
0.6414523245988089


In [17]:
linereg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [18]:
linereg.coef_

array([44467.94759687])

In [19]:
#X_pred.head()

In [20]:
holdout_set.head()

Id        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0  2658  902301120          190        RM          69.0      9142   Pave   
1  2718  905108090           90        RL           NaN      9662   Pave   
2  2414  528218130           60        RL          58.0     17104   Pave   
3  1989  902207150           30        RM          60.0      8520   Pave   
4   625  535105100           20        RL           NaN      9500   Pave   

  Alley Lot Shape Land Contour    ...     3Ssn Porch Screen Porch Pool Area  \
0  Grvl       Reg          Lvl    ...              0            0         0   
1   NaN       IR1          Lvl    ...              0            0         0   
2   NaN       IR1          Lvl    ...              0            0         0   
3   NaN       Reg          Lvl    ...              0            0         0   
4   NaN       IR1          Lvl    ...              0          185         0   

  Pool QC Fence Misc Feature Misc Val Mo Sold  Yr Sold  Sale Type  
0     NaN   NaN          NaN        0       4     2006        WD   
1     NaN   NaN          NaN        0       8     2006        WD   
2     NaN   NaN          NaN        0       9     2006        New  
3     NaN   NaN          NaN        0       7     2007        WD   
4     NaN   NaN          NaN        0       7     2009        WD   

[5 rows x 80 columns]

In [21]:
X_pred = pd.DataFrame(holdout_set['Overall Qual'])

In [22]:
y_preds =linereg.predict(X_pred)

y_preds

array([176483.04731971, 132015.09972284, 220950.99491658, 132015.09972284,
       176483.04731971,  87547.15212597,  87547.15212597, 132015.09972284,
       220950.99491658, 176483.04731971, 176483.04731971, 176483.04731971,
       176483.04731971, 220950.99491658, 176483.04731971, 132015.09972284,
       176483.04731971, 132015.09972284, 176483.04731971, 265418.94251345,
       132015.09972284, 132015.09972284, 176483.04731971, 176483.04731971,
       220950.99491658, 132015.09972284,  87547.15212597, 132015.09972284,
       176483.04731971,  43079.2045291 ,  87547.15212597,  87547.15212597,
       220950.99491658, 132015.09972284, 220950.99491658, 220950.99491658,
        87547.15212597,  87547.15212597, 132015.09972284, 220950.99491658,
       176483.04731971, 220950.99491658, 132015.09972284, 132015.09972284,
       220950.99491658,  87547.15212597, 220950.99491658, 132015.09972284,
       132015.09972284, 132015.09972284, 132015.09972284, 265418.94251345,
       265418.94251345, 1

In [23]:
pd.read_csv('sample_sub_reg.csv', index_col='Id')

SalePrice
Id               
2     181479.1217
4     181479.1217
6     181479.1217
7     181479.1217
17    181479.1217
18    181479.1217
22    181479.1217
27    181479.1217
31    181479.1217
36    181479.1217
39    181479.1217
40    181479.1217
42    181479.1217
46    181479.1217
53    181479.1217
58    181479.1217
61    181479.1217
72    181479.1217
79    181479.1217
80    181479.1217
82    181479.1217
83    181479.1217
85    181479.1217
88    181479.1217
92    181479.1217
93    181479.1217
95    181479.1217
102   181479.1217
103   181479.1217
106   181479.1217
...           ...
2825  181479.1217
2828  181479.1217
2831  181479.1217
2843  181479.1217
2845  181479.1217
2847  181479.1217
2855  181479.1217
2856  181479.1217
2859  181479.1217
2865  181479.1217
2867  181479.1217
2869  181479.1217
2870  181479.1217
2874  181479.1217
2876  181479.1217
2889  181479.1217
2892  181479.1217
2895  181479.1217
2898  181479.1217
2901  181479.1217
2902  181479.1217
2908  181479.1217
2909  181479.1217
2916  181479.1217
2917  181479.1217
2919  181479.1217
2921  181479.1217
2922  181479.1217
2925  181479.1217
2928  181479.1217

[879 rows x 1 columns]

In [24]:
df= pd.DataFrame()

In [25]:
myids= holdout_set['Id']

In [26]:
df['Id']=myids

In [27]:
df.head()

Id
0  2658
1  2718
2  2414
3  1989
4   625

In [28]:
df['SalePrice']=y_preds

In [29]:
df

Id      SalePrice
0    2658  176483.047320
1    2718  132015.099723
2    2414  220950.994917
3    1989  132015.099723
4     625  176483.047320
5     333   87547.152126
6    1327   87547.152126
7     858  132015.099723
8      95  220950.994917
9    1568  176483.047320
10   2482  176483.047320
11   1364  176483.047320
12   2584  176483.047320
13    818  220950.994917
14   2673  176483.047320
15   2089  132015.099723
16   1297  176483.047320
17    790  132015.099723
18   2616  176483.047320
19    720  265418.942513
20    222  132015.099723
21    557  132015.099723
22   1148  176483.047320
23   2766  176483.047320
24    534  220950.994917
25   1452  132015.099723
26    630   87547.152126
27   2648  132015.099723
28    125  176483.047320
29   1904   43079.204529
..    ...            ...
849   933  176483.047320
850  2784  176483.047320
851   972  176483.047320
852   599  176483.047320
853  2614  176483.047320
854  2582  132015.099723
855  1409  176483.047320
856   175   43079.204529
857   352  265418.942513
858   976   87547.152126
859  2134  220950.994917
860   984  132015.099723
861  2396  309886.890110
862  1673  220950.994917
863   404  132015.099723
864   607  132015.099723
865   814  132015.099723
866   868  220950.994917
867  2271  176483.047320
868  1633  220950.994917
869   337  132015.099723
870  2765  132015.099723
871  1746  220950.994917
872   368  265418.942513
873  2806  220950.994917
874  1662  176483.047320
875  1234  176483.047320
876  1373  132015.099723
877  1672   87547.152126
878  1939  132015.099723

[879 rows x 2 columns]

In [30]:
df.set_index('Id', inplace= True)

In [31]:
df.to_csv('./my_preds2.csv')